name: Ethrex Latest Release

on:
  release:
    types:
      - edited

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: manuelbilbao/ethrex

jobs:
  get_latest_release:
    name: "Get latest release tag"
    runs-on: ubuntu-latest

    steps:
      - name: Get latest release tag from GH API
        run: |
          tag=$(curl -s https://api.github.com/repos/manuelbilbao/ethrex/releases/latest | jq -r .tag_name)
          echo "latest_tag=$tag" >> $GITHUB_OUTPUT

  retag_docker_images:
    name: "Tag latest Docker images"
    runs-on: ubuntu-latest
    needs: [get_latest_release]
    if: ${{ jobs.get_latest_release.outputs.latest_tag == github.event.release.tag_name }}

    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Docker images
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name.from }}
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name.from }}-l2

      - name: Retag Docker images
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name.from }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name.from }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name.from }}-l2 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:l2
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name.from }}-l2 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}-l2

      - name: Push retagged Docker images
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}-l2
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:l2
